### ISSUE TITLE
Create Location Model

### ISSUE THREAD

**Issue by CSheesley** [CSheesley/ccs_cross_poll_backend#5]
`rails g migrate CreateLocation`

In the migration add the following attributes

      name: STRING
      phone: INTEGER
      address: STRING
      city: STRING 
      state: STRING
      zip: INTEGER
      office_hours: STRING
      lat: FLOAT
      lng: FLOAT

[] Model Validation Spec
Using `validates_presence_of`

*don't require phone, or office hours - a location can be created without this information

**Comment by SallyH3** [comment]
The following attributes have been included in the `Location` model: 
```
  name: STRING
  phone: INTEGER
  address: STRING
  city: STRING 
  state: STRING
  zip: INTEGER
  office_hours: STRING
  lat: FLOAT
  lng: FLOAT
```
