### ISSUE TITLE
Create Location Seed File

### ISSUE THREAD

**Issue by CSheesley** [CSheesley/ccs_cross_poll_backend#6]
Create a Seed File for `Location` model.

Fit this pattern
```
      "name": "Denver Walk-In Crisis Services",
      "phone": 3035041299,
      "address": "4353 E. Colfax Avenue",
      "city": "Denver", 
      "state": "CO", 
      "zip": 80220,
      "hours": "24 hours a day, 7 days a week",
      "lat": 39.7403,
      "lng": -104.9363
```
[] Seed Database, confirm it worked!

**Comment by SallyH3** [comment]
Created seed file for `Location` model complete in above format however, instead of "address", I put "street" and for "hours": "24/7" instead of 24 hrs a day, 7 days a week. 
**TODO**: Confirm it worked with `rake db:seed`
